### ISSUE TITLE
Expected 2D array, got 1D array instead: array=[].

### ISSUE THREAD

**Issue by leenaraz** [elcorto/imagecluster#10]
when running
 fps = ic.pca(fps, n_components=0.95)
i get the following error

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leena/mainproject/imagecluster/imagecluster/calc.py", line 185, in pca
    Xp = PCA(**kwds).fit(X).transform(X)
  File "/usr/lib/python3/dist-packages/sklearn/decomposition/pca.py", line 329, in fit
    self._fit(X)
  File "/usr/lib/python3/dist-packages/sklearn/decomposition/pca.py", line 370, in _fit
    copy=self.copy)
  File "/usr/lib/python3/dist-packages/sklearn/utils/validation.py", line 441, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.**

**Comment by elcorto** [comment]
What verions of the packages in `requirements.txt` do you use?

**Comment by leenaraz** [comment]
I found the solution. It was my bad the images were saves in a sub folder in pics. i copied it and the issue was solved.
