### ISSUE TITLE
OSError: image file is truncated (30 bytes not processed)

### ISSUE THREAD

**Issue by kamelito78** [elcorto/imagecluster#3]
I launched your algorithm with this code on 200 pictures :

#!/usr/bin/env python3
from imagecluster import main
main.main('/tmp/pictures/', sim=0.5)

I got this error :

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    main.main('/tmp/pictures/', sim=0.5)
  File "/tmp/imagecluster/imagecluster/main.py", line 28, in main
    fps = ic.fingerprints(files, model, size=(224,224))
  File "/tmp/imagecluster/imagecluster/imagecluster.py", line 131, in fingerprints
    return dict((fn, fingerprint(fn, model, size)) for fn in files)
  File "/tmp/imagecluster/imagecluster/imagecluster.py", line 131, in <genexpr>
    return dict((fn, fingerprint(fn, model, size)) for fn in files)
  File "/tmp/imagecluster/imagecluster/imagecluster.py", line 67, in fingerprint
    img = PIL.Image.open(fn).resize(size, 2)
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 1747, in resize
    self.load()
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageFile.py", line 228, in load
    "(%d bytes not processed)" % len(b))
OSError: image file is truncated (30 bytes not processed)

**Comment by elcorto** [comment]
This looks like a PIL issue to me. The first search result I get is https://stackoverflow.com/a/23575498. I'm using the Pillow version of PIL (v4.3). I'll add that to `setup.py`.
