### ISSUE TITLE
error on shape size (224, 224, 4) maybe related to keras/tenserflow versions?

### ISSUE THREAD

**Issue by idanr1986** [elcorto/imagecluster#5]
======================================================================
ERROR: Failure: ValueError (Error when checking input: expected input_2 to have shape (224, 224, 3) but got array with shape (224, 224, 4))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/mobile/imagecluster/test.py", line 2, in <module>
    main.main('/home/mobile/app_icons/images', sim=0.5)
  File "/home/mobile/imagecluster/imagecluster/main.py", line 28, in main
    fps = ic.fingerprints(files, model, size=(224,224))
  File "/home/mobile/imagecluster/imagecluster/imagecluster.py", line 131, in fingerprints
    return dict((fn, fingerprint(fn, model, size)) for fn in files)
  File "/home/mobile/imagecluster/imagecluster/imagecluster.py", line 131, in <genexpr>
    return dict((fn, fingerprint(fn, model, size)) for fn in files)
  File "/home/mobile/imagecluster/imagecluster/imagecluster.py", line 90, in fingerprint
    return model.predict(arr4d_pp)[0,:]
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1147, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 749, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_utils.py", line 137, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_2 to have shape (224, 224, 3) but got array with shape (224, 224, 4)
-------------------- >> begin captured logging << --------------------
PIL.PngImagePlugin: DEBUG: STREAM b'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM b'IDAT' 41 6482
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 2 tests in 33.882s

FAILED (errors=1)

**Comment by elcorto** [comment]
Hard to say with nothing but a traceback. Some more context would certainly help, for instance: Does the simple test imagecluster/test/test_ic.py pass? What code are you running to produce this error? What version of keras/tensorflow are you using?

**Comment by elcorto** [comment]
Closing due to inactive OP.

**Comment by UsaidPro** [comment]
I got the same error, and I discovered it happens when the main.main() function gets a PNG rather than a JPEG.

**Comment by elcorto** [comment]
That happens when the PNG is in RGBA mode, the fourth channel is the alpha channel. So far I processed only JPGs. The very quick fix would be to remove alpha and set a white background before, e.g. `convert -alpha deactivate -background white foo.png foo.jpg`.

**Comment by UsaidPro** [comment]
Yeah, I realized that. Thanks for the solution to convert PNG to JPG. This
issue can be closed now (sorry about resurrecting a closed issue).

**Comment by elcorto** [comment]
I'll leave that open as a reminder. I'll add a PIL way to convert RGBA -> RBG when I have the time. Thanks for reporting.

**Comment by elcorto** [comment]
> `convert -alpha deactivate -background white foo.png foo.jpg`.

That should read `-alpha remove`.
